### ISSUE TITLE
您好,我在使用libtorch推理时,一直有一个错误

### ISSUE THREAD

**Issue by DeepSpace98** [NagatoYuki0943/anomalib-libtorch#1]
`auto result = inference(model, x);`推理的时候,这句一直报错.
vs显示下面这个
`0x00007FFE05023B19 处(位于 TorchProject1.exe 中)引发的异常: Microsoft C++ 异常: c10::Error，位于内存位置 0x0000009E6F3FB080 处。`
`Debug Error!`
`Program: D:\Game\TorchProject1\x64\Debug\TorchProject1.exe
abort() has been calle`
程序显示在IListRef.h出现了断点,即下面这里
`#if defined(_MSC_VER) && _ITERATOR_DEBUG_LEVEL == 2`
 ` // See [Note: MSVC Iterator Debug]`
`  ~IListRefIterator() {`
 `   switch (tag_) {`
`      case IListRefTag::Boxed:`
`        payload_.boxed_iterator.~boxed_iterator_type();`
`      case IListRefTag::Unboxed:`
`        payload_.unboxed_iterator.~unboxed_iterator_type();`
`      default:`
`        TORCH_INTERNAL_ASSERT(false, "invalid IListRef tag.");`
`    }`
您能帮我看看哪里有问题吗?

**Comment by NagatoYuki0943** [comment]
这个博客有一些说明,可以先看看,我当时也遇见过,我明天看一下,https://blog.csdn.net/zzz_zzz12138/article/details/109138805

**Comment by NagatoYuki0943** [comment]
https://github.com/NagatoYuki0943/anomalib-libtorch/blob/31dec3a7d4246f2f86ef3a4c7374f0eaa2233a57/%E6%BA%90.cpp#L307 这一行用了cuda,你试试直接设置为false一下,如果false可以说明是cuda的问题,要在vs的链接器命令中添加一些命令才行

**Comment by DeepSpace98** [comment]
> 

大佬,可以加个qq吗?2778709580

**Comment by Sherlock-hh** [comment]
你好你好，我也碰到一样的问题，看了大佬你推荐的博客，但是没找到是咋解决的，想问一下是怎么解决的呀？

> 这个博客有一些说明,可以先看看,我当时也遇见过,我明天看一下,https://blog.csdn.net/zzz_zzz12138/article/details/109138805
